version: "3"

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce
    ports:
      - "8082:80"
      - "2222:22"
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_logs:/var/log/gitlab
      - gitlab_data:/var/opt/gitlab

  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - jenkins_data:/var/jenkins_home
  jira:
    container_name: jira
    restart: always
    image: cptactionhank/atlassian-jira:7.7.0
    ports:
      - '80:8080'
    volumes:
      - jira-data:/var/atlassian/jira  # JIRA_HOME
  mysql:
    container_name: mysql
    restart: always
    image: mysql:5
    environment:
      - MYSQL_ROOT_PASSWORD=1q2w3e4r
      - MYSQL_DATABASE=jiradb          
      - MYSQL_USER=jira                
      - MYSQL_PASSWORD=jiradb
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  jenkins_data:
  mysql-data:
  jira-data:
  gitlab_config:
  gitlab_logs:
  gitlab_data:

